calendar_manager/accounts/urls.py
from django.urls import path
from django.contrib import admin
from accounts.views import signup
from accounts.views import signin
from accounts.views import signout

app_name = 'accounts'


urlpatterns = [
    path('signup/', signup.SignUpView.as_view(), name='signup'),
    path('signin/', signin.SignInView.as_view(), name='signin'),
    path('signout/', signout.signout, name='signout'),
]

calendar_manager/calendar_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from calendar_manager.views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include("events_calendar.urls")),
]

calendar_manager/events_calendar/urls.py
from django.urls import path

from events_calendar.views.event_list import AllEventsListView, RunningEventsListView
from events_calendar.views.other_views import CalendarViewNew, CalendarView, create_event, EventEdit, event_details, load_event
from events_calendar.views.other_views import *

app_name = "events_calendar"

urlpatterns = [
    path("calendar/", CalendarViewNew.as_view(), name="calendar"),
    path("calendars/", CalendarView.as_view(), name="calendars"),
    path("event/new/", create_event, name="event_new"),
    path("event/edit/<int:pk>/", EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        RunningEventsListView.as_view(),
        name="running_events",
    ),
    path("load/calendar", load_event,name="load_ctt"),
    path("export/data/<int:pk>", export_data_of_group, name="export_data"),
    path("create/group", create_group, name="add_group"),
    path("view/group", view_group, name="view_group"),
    path("list_detail/groupmember/<int:pk>/", list_detail_group, name="list_detail_groupmember"),
    path("add/member/groupmember/<int:pk>/", add_member_group, name="add_group_member"),
    path("remove/member/groupmember/<int:pk>/", remove_member_group, name="remove_member_group"),
    path("remove/event/groupevent/<int:pk>/", remove_event_group, name='remove_event_group'),
    path("calendar/groupmember/<int:pk>/", GroupCalendarView.as_view(), name="calendar_group_member"),
    path("connect_google_calendar/", load_data_google_calendar, name="connect_google_calendar")
]

calendar_manager/templates/add_group.html
{% extends 'base/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'events_calendar:calendar' %}"> Calendar </a>
</div>

<form method="post" style="padding: 5px 190px; ">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendar_manager/templates/add_member.html
{% extends 'base/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'events_calendar:calendar' %}"> Calendar </a>
</div>

<form method="post" style="padding: 5px 190px;">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendar_manager/templates/add_member_group.html
{% extends 'base/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'events_calendar:calendar' %}">Group Calendar </a>
</div>

<form method="post" style="padding: 5px 190px; ">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendar_manager/templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

calendar_manager/templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Wellcome, {{ request.user }}</span>
    <a class="btn btn-info right" href="{% url 'accounts:signout' %}"> Sign Out</a>
	<a class="btn btn-info right mr-2" href="{% url 'events_calendar:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'events_calendar:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    <a class="btn btn-info right mr-2" href="{% url 'events_calendar:event_new' %}"> + New Event </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

calendar_manager/templates/event.html
{% extends 'base/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'events_calendar:calendar' %}"> Calendar </a>
</div>

<form method="post" style="padding: 5px 190px; ">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr style="text-align: center; "><td colspan="2"><button style="margin-top: 10px;" type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendar_manager/templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'base/base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

calendar_manager/templates/event_details.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}

Event Details
{% endblock %}

{% block extracss %}

{% endblock extracss %}

{% block content %}
    <div style="height: 100vh; background-image:linear-gradient(rgba(255,255,255,0.75), rgba(255,255,255,0.75)),  url('https://ctsv.hust.edu.vn/static/img/banner-home.d4038b4b.png?fbclid=IwAR0y7mCDcx1JqR3kltei1qyWR-QXoAv5S16Rm5qK2lNa7aeab6qmqEJfpRc') ;" >
        <div class="container" >
            <div class="clearfix" >
                <a class="btn btn-primary left" href="{% url 'events_calendar:calendar' %}"> Calendar </a>
                <a class="btn btn-info right mr-3" style="float:right; border: none ; background-color: #990000;" href="{% url 'events_calendar:remove_event' event.pk%}">Delete Event</a>
                <a class="btn btn-info right mr-2" style="float:right; border: none ; " href="{% url 'events_calendar:event_edit' event.pk %}"> Edit Event </a>
            </div>
    
            <div class="clearfix">
                <h3>Event Name: {{ event.title }}</h3>
                <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
                <hr>
                <p>{{ event.description }}</p>
            </div>
            <hr>
            <div class="clearfix">
                <a style="font-size: 22px; font-weight: 600;" class="" > Members of this Event</a>
                <a class="btn btn-success " style="float:right; border: none ;" href="{% url 'events_calendar:add_eventmember' event.id %}"> Add Member </a>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>Name</th>
                      <th>Username</th>
                      <th>Email</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for member in eventmember %}
                    <tr role="row">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                        <td>{{ member.user.username }}</td>
                        <td>{{ member.user.email }}</td>
                        <td>
                            <a class="btn btn-danger" href="{% url 'events_calendar:remove_event' member.id %}">Remove</a>
                        </td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
        </div>
    </div>
    
{% endblock %}

calendar_manager/templates/group_event.html
{% extends 'base/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'events_calendar:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendar_manager/templates/list_detail_group.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Time Management System{% endblock title %}

{% block extracss %}
  <link href="{% static 'calendar/main.css' %}" rel="stylesheet" />
{% endblock extracss %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'events_calendar:calendar_group_member' group.id %}"> Calendar Group </a>
        </div>

        <div class="clearfix">
            <h3>Group Name: {{ group.name }}</h3>
            <p>From <span style="color: gray;"></span> To <span style="color: gray;"></span></p>
            <hr>
            <p>Description: Try Hard</p>
        </div>
        <hr>
        <div class="clearfix">
            <a style="font-size: 22px; font-weight: 600;" class="" > Members of group</a>
            <a class="btn btn-success " style="float:right; border: none ;" href="{% url 'events_calendar:add_group_member' group.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th style="width: 10px">STT</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Leader</th>
                  <th>Remove Member</th>
                </tr>
              </thead>
              <tbody>
                {% for member in groupmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email}}</td>
                    <td>{{ member.is_leader }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'events_calendar:remove_member_group' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>

        <div class="clearfix">
            <h4 class="left">List Event of group:</h4>
        </div>
        <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 102.102px;">STT</th>
                    <th href="#" class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 200.312px;">Event Name</th>
                    <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 200.281px;">Start Time</th>
                    <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 200.281px;">End Time</th>
                    <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for event in list_event %}
                    <tr role="row" class="odd">
                        <td class="sorting_1">{{ forloop.counter }}</td>
                        <td>{{ event.title }}</td>
                        <td>{{ event.start_time }}</td>
                        <td>{{ event.end_time }}</td>
                        <td>
                            <a class="btn btn-danger" href="{% url 'events_calendar:remove_event_group' event.id %}">Remove</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

calendar_manager/templates/view_group.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> View Group</h1>
        <p></p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a class="btn btn-info right mr-2" href="{% url 'events_calendar:add_group' %}">Add Group +</a></li>
    </ul>

{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 261.641px;">SL</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 417.312px;">Group Name</th>
                                           
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for group in groups %}
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{ forloop.counter }}</td>
                                                <td ><a style='color: blue;' href="{% url 'events_calendar:list_detail_groupmember' group.id %}"><div style="height:100%;width:100%">{{ group.name }}</div></td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}