calendar_manager/accounts/urls.py
from django.urls import path
from django.contrib import admin
from accounts.views import signup
from accounts.views import signin
from accounts.views import signout

app_name = 'accounts'


urlpatterns = [
    path('signup/', signup.SignUpView.as_view(), name='signup'),
    path('signin/', signin.SignInView.as_view(), name='signin'),
    path('signout/', signout.signout, name='signout'),
]

calendar_manager/calendar_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from calendar_manager.views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include("events_calendar.urls")),
]

calendar_manager/events_calendar/urls.py
from django.urls import path

from events_calendar.views.event_list import AllEventsListView, RunningEventsListView
from events_calendar.views.other_views import CalendarViewNew, CalendarView, create_event, EventEdit, event_details, load_event
from events_calendar.views.other_views import *

app_name = "events_calendar"

urlpatterns = [
    path("calendar/", CalendarViewNew.as_view(), name="calendar"),
    path("calendars/", CalendarView.as_view(), name="calendars"),
    path("event/new/", create_event, name="event_new"),
    path("event/edit/<int:pk>/", EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        RunningEventsListView.as_view(),
        name="running_events",
    ),
    path("load/calendar", load_event,name="load_ctt"),
    path("export/data/<int:pk>", export_data_of_group, name="export_data"),
    path("create/group", create_group, name="add_group"),
    path("view/group", view_group, name="view_group"),
    path("list_detail/groupmember/<int:pk>/", list_detail_group, name="list_detail_groupmember"),
    path("add/member/groupmember/<int:pk>/", add_member_group, name="add_group_member"),
    path("remove/member/groupmember/<int:pk>/", remove_member_group, name="remove_member_group"),
    path("remove/event/groupevent/<int:pk>/", remove_event_group, name='remove_event_group'),
    path("calendar/groupmember/<int:pk>/", GroupCalendarView.as_view(), name="calendar_group_member"),
    path("connect_google_calendar/", load_data_google_calendar, name="connect_google_calendar")
]

calendar_manager/templates/group_calendar/calendar.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Time Management System{% endblock title %}

{% block extracss %}
  <link href="{% static 'calendar/main.css' %}" rel="stylesheet" />
{% endblock extracss %}

{% block breadcrumb %}
  <div>
      <h1><i class="fa fa-calendar"></i> Calendar</h1>
      <p>Time Management System</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
      <!-- <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li> -->
      <li class="breadcrumb-item"><a style="font-weight: 600;color: #fff; background-color: #009688; padding: 5px 10px; border: solid 1px; border-radius: 5px ;" href="{% url 'events_calendar:export_data' pk %}">Recommend DateTime</a></li>
  </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile row">
            <div class="col-md-3">
                <div id="external-events">
                    <h2 class="mb-4">Group name : {{ name_group }} </h2>
                    <h4 class="mb-2">Members:</h4>
                    {% for member in members %}
                      <div class="fc-event" style="background-color:{{ member.color }}">
                          <h4 style="font-size: 13px !important; margin-bottom: 0px; ">{{ member.user.email }}</h4>
                          <p></p>
                      </div>
                    {% empty %}
                      <p>No Member in Group</p>
                    {% endfor %}
                    <h4 class="mb-3">Group:</h4>
                    <div class="fc-event" style="background-color: rgb(82, 20, 76)">
                      <h5 style="font-size: 13px !important; margin-bottom: 0px; ">Metting of: {{ name_group }}</h5>
                      <p></p>
                    </div>
                    {% if check_recommend != 0 %}
                    <h4 class="mb-2">Recommend datetime:</h4>
                    <div class="fc-event" style="background-color: rgba(218, 167, 15, 0.692)">
                      <h4> {{ name_group }}</h4>
                      <p></p>
                    </div>
                    {% endif %}
                </div>
                
            </div>
            <div class="col-md-9">
                <div id="calendar"></div>
            </div>

            <div class="modal fade show" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-primary">
                            <h5 class="modal-title text-white" id="exampleModalLongTitle">Add New Event</h5>
                            <button id="modalClose1" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Event Title:</label>
                                    {{ form.title }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Description:</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Start Date:</label>
                                    {{ form.start_time }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">End Date:</label>
                                    {{ form.end_time }}
                                </div>
                                <div class="form-group">
                                  <label for="message-text" class="col-form-label">Group:</label>
                                  {{ form.group }}
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button id="modalClose2" type="button" class="btn btn-danger">Close</button>
                                <button name="event_add_1" type="submit" value="Submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
  <script src="{% static 'calendar/main.js' %}"></script>
  <script src="{% static 'calender/main.js' %}"></script>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var today = new Date();

        var calendar = new FullCalendar.Calendar(calendarEl, {
          headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
          },
          initialView: 'timeGridWeek',
          initialDate: today,
          navLinks: true, // can click day/week names to navigate views
          selectable: true,
          selectMirror: true,
          select: function(arg) {
            console.log('clicked')
            var modal = document.getElementById('eventModal')
            modal.style.display = 'block'
            calendar.unselect()
          },
          // THIS KEY WON'T WORK IN PRODUCTION!!!
          // To make your own Google API key, follow the directions here:
          // http://fullcalendar.io/docs/google_calendar/
          // googleCalendarApiKey: 'AIzaSyCqCxjjLtjbtkX37aOtWB8OfwBLy_6QuYk',

          // bangladesh Holidays
          // events: 'bn.bd#holiday@group.v.calendar.google.com',
          eventClick: function(arg) {
            arg.event.remove()
          },
          editable: true,
          dayMaxEvents: true, // allow "more" link when too many events
          events: {{ events|safe }},

        });
        calendar.render();
      });
      const closeBtn1 = document.getElementById('modalClose1');
      const closeBtn2 = document.getElementById('modalClose2');
      closeBtn1.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
      closeBtn2.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
  </script>
{% endblock extrascripts %}

calendar_manager/templates/group_calendar/recommend_calendar.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Time Management System{% endblock title %}

{% block extracss %}
  <link href="{% static 'calendar/main.css' %}" rel="stylesheet" />
{% endblock extracss %}

{% block content %}
    <div class="modal-header bg-primary">
        <h5 class="modal-title text-white" id="exampleModalLongTitle">Choose The Time Period By Week : </h5>
        <button id="modalClose1" type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form method="post" style="padding: 5px 190px; ">
        {% csrf_token %}
        <div class="modal-body">
            <div class="form-group">
                <label for="message-text" class="col-form-label">Start Date:</label>
                {{ form.start_time }}
            </div>
            <div class="form-group">
                <label for="message-text" class="col-form-label">End Date:</label>
                {{ form.end_time }}
            </div>

        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Recommend Date</button>
        </div>
    </form>
{% endblock content %}

{% block extrascripts %}
    <script src="{% static 'calendar/main.js' %}"></script>
    <script src="{% static 'calender/main.js' %}"></script>
{% endblock extrascripts %}