calendar_manager/accounts/urls.py
from django.urls import path
from django.contrib import admin
from accounts.views import signup
from accounts.views import signin
from accounts.views import signout

app_name = 'accounts'


urlpatterns = [
    path('signup/', signup.SignUpView.as_view(), name='signup'),
    path('signin/', signin.SignInView.as_view(), name='signin'),
    path('signout/', signout.signout, name='signout'),
]

calendar_manager/calendar_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from calendar_manager.views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include("events_calendar.urls")),
]

calendar_manager/events_calendar/urls.py
from django.urls import path

from events_calendar.views.event_list import AllEventsListView, RunningEventsListView
from events_calendar.views.other_views import CalendarViewNew, CalendarView, create_event, EventEdit, event_details, load_event
from events_calendar.views.other_views import *

app_name = "events_calendar"

urlpatterns = [
    path("calendar/", CalendarViewNew.as_view(), name="calendar"),
    path("calendars/", CalendarView.as_view(), name="calendars"),
    path("event/new/", create_event, name="event_new"),
    path("event/edit/<int:pk>/", EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        RunningEventsListView.as_view(),
        name="running_events",
    ),
    path("load/calendar", load_event,name="load_ctt"),
    path("export/data/<int:pk>", export_data_of_group, name="export_data"),
    path("create/group", create_group, name="add_group"),
    path("view/group", view_group, name="view_group"),
    path("list_detail/groupmember/<int:pk>/", list_detail_group, name="list_detail_groupmember"),
    path("add/member/groupmember/<int:pk>/", add_member_group, name="add_group_member"),
    path("remove/member/groupmember/<int:pk>/", remove_member_group, name="remove_member_group"),
    path("remove/event/groupevent/<int:pk>/", remove_event_group, name='remove_event_group'),
    path("calendar/groupmember/<int:pk>/", GroupCalendarView.as_view(), name="calendar_group_member"),
    path("connect_google_calendar/", load_data_google_calendar, name="connect_google_calendar")
]

calendar_manager/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta name="description" content="Event Dashboard" />
        <meta property="og:description" content="Event Dashboard" />
        <title>{% block title %}Calendar{% endblock title  %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body class="app sidebar-mini">
        <!-- Navbar-->
        <header class="app-header" style="background-color: #990000 !important;">
            <a class="app-header__logo" style="background-color: #990000 !important;" href="#">TMS</a>
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <li class="app-search">
                    <input class="app-search__input" type="search" placeholder="Search" />
                    <button class="app-search__button"><i class="fa fa-search"></i></button>
                </li>
                <!--Notification Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Show notifications"><i class="fa fa-bell-o fa-lg"></i></a>
                    <ul class="app-notification dropdown-menu dropdown-menu-right">
                        <li class="app-notification__title">You have 4 new notifications.</li>
                        <div class="app-notification__content">
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message">Lisa sent you a mail</p>
                                        <p class="app-notification__meta">2 min ago</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message">Mail server not working</p>
                                        <p class="app-notification__meta">5 min ago</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message">Transaction complete</p>
                                        <p class="app-notification__meta">2 days ago</p>
                                    </div>
                                </a>
                            </li>
                            <div class="app-notification__content">
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">Lisa sent you a mail</p>
                                            <p class="app-notification__meta">2 min ago</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">Mail server not working</p>
                                            <p class="app-notification__meta">5 min ago</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">Transaction complete</p>
                                            <p class="app-notification__meta">2 days ago</p>
                                        </div>
                                    </a>
                                </li>
                            </div>
                        </div>
                        <li class="app-notification__footer"><a href="#">See all notifications.</a></li>
                    </ul>
                </li>
                <!-- User Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="#"><i class="fa fa-cog fa-lg"></i> Settings</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#"><i class="fa fa-user fa-lg"></i> Profile</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="fa fa-sign-out fa-lg"></i> Sign Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <div class="app-sidebar__user">
                <img class="member.user.first_name" src="https://upload.wikimedia.org/wikipedia/commons/b/b8/Messi_vs_Nigeria_2018.jpg" alt="User Image" height="50px" width="50px"/>
                <div>
                    <p class="app-sidebar__user-name">Team13</p>
                    <p class="app-sidebar__user-designation">Calendar</p>
                </div>
            </div>
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item active" href="{% url 'dashboard' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'events_calendar:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Calendar</span></a>
                </li>
                <li class="treeview">
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Events</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'events_calendar:running_events' %}"><i class="icon fad fa-running"></i> Running</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'events_calendar:running_events' %}"><i class="icon fad fa-running"></i> Upcoming</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'events_calendar:all_events' %}"><i class="icon fad fa-running"></i> All</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'events_calendar:view_group' %}"><i class="app-menu__icon fa fa-users"></i><span class="app-menu__label">Group Calendar</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'events_calendar:load_ctt' %}"><i class="app-menu__icon fa fa-refresh"></i><span class="app-menu__label">Activate integration</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="http://localhost:3000"><i class="app-menu__icon fa fa-graduation-cap"></i><span class="app-menu__label">Class-Activities System</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'events_calendar:connect_google_calendar' %}"><i class="app-menu__icon fa fa-google"></i><span class="app-menu__label">Google Calendar</span></a>
                </li>

            </ul>
        </aside>
        <main class="app-content">
            <div class="app-title">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>

calendar_manager/templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>